name: Broadcast
main: me.es359.Broadcast.Broadcast
version: 3.0.3
description: Custom Broadcast plugin for server admins!
author: __ES
website: http://www.spigotmc.org/resources/broadcast.5747/

commands:
  broadcast:
    description: Main command for plugin.
    aliases: [b,alert,yell,bc]
  sb:
    description: Main command for staff members.
    aliases: [mb, heyadmin, staffyelling,sc]
  shout:
    description: Public broadcast feature for server users.
    aliases: [y, hey, a]
  report:
    description: Command to report a rule breaker.
    aliases: []